In [1]:
#-------------------------------------------------------------------------------------------------------#
#                                               FAKHR BASHA                                             #   
#-------------------------------------------------------------------------------------------------------#

Hello


In [3]:
#-------------------------------------------------------------------------------------------------------#
#                                               FAKHR BASHA                                             #   
#-------------------------------------------------------------------------------------------------------#
import numpy as np

In [5]:
print(np.__version__)

1.21.5


In [9]:
arr = np.array([1,2,3,4])
print(arr) # [1 2 3 4]
print(type(arr)) # numpy.ndarray

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
zero_D = np.array([24])
one_D = np.array([1,2,3,4,5])

two_D = np.array([[1,2,3],[4,5,6]])

three_D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])


NameError: name 'np' is not defined

In [15]:
print(zero_D)

[24]


In [17]:
print(one_D)
print(two_D)
print(three_D)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
print(two_D)

[[1 2 3]
 [4 5 6]]


In [21]:
print(three_D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [23]:
print(one_D.ndim) #1
print(two_D.ndim) #2
print(three_D.ndim) #3

1
2
3


In [33]:
arr = np.array([1,2,3,4,5] , ndmin=5 )
print(arr)
print(" the number dimensions is :  " ,  arr.ndim)

[[[[[1 2 3 4 5]]]]]
 the number dimensions is :   5


In [45]:
# indexing
print(one_D[0]) #1
print(two_D[1][0]) #4
print(one_D[1] + two_D[0][2]) # 2 + 3

1
4
5


In [47]:
# Slicing
arr = np.array([1,2,3,4,5,6,7])
# slice 2 3 4 5
# (start:end)
# (start:end:step)
print(arr[1:5])

[2 3 4 5]


In [49]:
# Slice elements from index 4 to the end of the array:
print(arr[4:])
# 5 6 7

[5 6 7]


In [51]:
# Slice elements from the beginning to index 4 (not included):
print(arr[:4])

[1 2 3 4]


In [55]:
print(arr[1:7:2]) 
# here step = 2 inc +=2 

[2 4 6]


In [59]:
# Slicing 2-D Arrays
arr = np.array([[1,2,3,7,8,9],[4,5,6,10,11,12]])
print(arr[1 , 1:4])

[ 5  6 10]


In [63]:
print(arr[0:2, 1:4])

[[ 2  3  7]
 [ 5  6 10]]


In [65]:
# data type
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [67]:
arr = np.array(["ahmeed","mohameed","salah"])
print(arr.dtype)

<U8


In [71]:
# Define Data Type
arr = np.array([1,2,3,4] ,dtype = 'S')
print (arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [77]:
# convert data type use astype()
arr = np.array([1.2,2.3,3.4])
new = arr.astype(int)
print(new)
print(new.dtype)
# ------- # 
b = np.array([1,0,3])
n = b.astype(bool)
print(n)

[1 2 3]
int64
[ True False  True]


In [79]:
# copy and veiw
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print (arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [83]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print (arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [12]:
import numpy as np
arr = np.array([[1,2,3,5,4],[5,6,5,47,8]])
print(arr)

[[ 1  2  3  5  4]
 [ 5  6  5 47  8]]


In [14]:
print(arr.shape)

(2, 5)


In [20]:
#Reshape

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = arr.reshape(4,3)
print(x.shape)
print(x)
    

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
# iterating
arr = np.array([1,2,3,4])
for i in arr:
    print(i)
# 1_D              

1
2
3
4


In [24]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    print (i)

[1 2 3]
[4 5 6]


In [26]:
arr = np.array([[1,2,3],[4,5,6]])
for i in arr:
    for x in i:
        print(x)
# 2_D

1
2
3
4
5
6


In [30]:
# Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in np.nditer(arr):
     print(i)

1
2
3
4
5
6
7
8


In [34]:
# join
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [40]:
arr = np.stack((arr1, arr2), axis=1)
print(arr)
# [1 4]
# [2 5] etc

[[1 4]
 [2 5]
 [3 6]]


In [42]:
arr = np.vstack((arr1,arr2))
print(arr)
# make 2D


[[1 2 3]
 [4 5 6]]
