In [1]:
#-------------------------------------------------------------------------------------------------------#
#                                               FAKHR BASHA                                             #   
#-------------------------------------------------------------------------------------------------------#
import numpy as np


In [5]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [7]:
a

array([1, 2, 3, 4])

In [11]:
print(a[0])

1


In [13]:
type(a)

numpy.ndarray

In [15]:
a.dtype


dtype('int64')

In [18]:
a.size

4

In [21]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print ('type : ' , b.dtype)
print ('number of dimensions = ' , b.ndim)
print ('shape = ' , b.shape)
print ('size = ' , b.size)

type :  int64
number of dimensions =  2
shape =  (2, 3)
size =  6


In [28]:
x = np.array(['1','2'])
x.astype(int)

array([1, 2])

In [31]:
np.full((4,4)  , [1,2,3,4])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [35]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [38]:
a = np.arange(4)
a


array([0, 1, 2, 3])

In [40]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [42]:
a+b

array([ 4,  6,  8, 10])

In [44]:
np.add(a,b)

array([ 4,  6,  8, 10])

In [46]:
a-b

array([-4, -4, -4, -4])

In [48]:
a*b

array([ 0,  5, 12, 21])

In [50]:
a = np.array([[4,5,6],[8,9,7]])
a.shape


(2, 3)

In [52]:
b = np.array([1,2,3])
b.shape

(3,)

In [56]:
c = np.dot(a,b)

c

array([32, 47])

In [58]:
c.shape

(2,)

In [62]:
z = np.array([
    [0, 1],
    [6, 7],
    [8, 9]
])
z.ravel()

array([0, 1, 6, 7, 8, 9])

In [73]:
a = np.arange(10,18).reshape((2,4))
a


array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [75]:
for i in a.flat:
    print(i)

10
11
12
13
14
15
16
17


In [77]:
a = np.random.random((4,4))
a

array([[0.03202844, 0.25765753, 0.00942023, 0.15494151],
       [0.81193971, 0.74030384, 0.68335221, 0.13092859],
       [0.76169228, 0.97420437, 0.16855851, 0.09366768],
       [0.58300403, 0.28919882, 0.487893  , 0.82563385]])

In [79]:
a < 0.2

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False, False]])

In [81]:
a [a < 0.2 ] # return value

array([0.03202844, 0.00942023, 0.15494151, 0.13092859, 0.16855851,
       0.09366768])

In [84]:
# split  / 
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
[b,c] = np.vsplit(a,2)

In [94]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
[b,c] = np.hsplit(a,2)

In [100]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [102]:
c


array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])